language: java

script: ./gradlew clean build

deploy:
  provider: script
  script: ./gradlew tag -Prelease bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY
  on:
    branch: master