language: java

jobs:
  include:
    - stage: deploy
      script: skip # skip re-running tests
      before_deploy: bash git-set-author.sh
      after_deploy: bash push-tags.sh
      deploy:
        provider: script
        skip_cleanup: true
        cleanup: false
        script: ./gradlew clean tag build bintrayUpload -Prelease -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY
        on:
          branch: master

stages:
  - name: deploy
    if: tag IS blank
