language: java

script: ./gradlew clean build tag -Prelease

deploy:
  provider: script
  skip_cleanup: true
  cleanup: false
  script: ./gradlew bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY
  on:
    branch: master

after_deploy: bash push-tags.sh
