language: java

branches:
  except:
    - /^v(\d+\.?){3}/
    - /^untagged/

jobs:
  include:
    - stage: test
      script: ./gradlew clean test

    - stage: deploy and release
      script: skip # skip re-running tests
      before_deploy: ./deploy.sh
      deploy:
        provider: releases
        skip_cleanup: true
        cleanup: false
        api_key: ${GH_TOKEN}
        file_glob: true
        file: "cli-bot/build/graal/faker-bot_*"
        on:
          branch: master

stages:
  - name: test
    if: NOT branch = master

  - name: deploy and release
    if: branch = master
