language: java

branches:
  except:
    - /^v(\d+\.?){3}/

jobs:
  include:
    - stage: deploy
      script: skip # skip re-running tests
      before_deploy: ./git-set-author.sh
      deploy:
        provider: script
        skip_cleanup: true
        cleanup: false
        script: ./deploy.sh
        on:
          branch: master

stages:
  - name: deploy
